# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Evi2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Evi2Dialog(object):
    def setupUi(self, Evi2Dialog):
        Evi2Dialog.setObjectName("Evi2Dialog")
        Evi2Dialog.resize(448, 403)
        self.buttonBox = QtWidgets.QDialogButtonBox(Evi2Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(140, 360, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(Evi2Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(8, 8, 431, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(6, 9, 411, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.RastercomboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.RastercomboBox.setGeometry(QtCore.QRect(70, 40, 301, 25))
        self.RastercomboBox.setObjectName("RastercomboBox")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 20))
        self.label.setObjectName("label")
        self.refreshButton = QtWidgets.QToolButton(self.groupBox_2)
        self.refreshButton.setGeometry(QtCore.QRect(380, 40, 26, 24))
        self.refreshButton.setText("")
        self.refreshButton.setObjectName("refreshButton")
        self.RGBradioButton = QtWidgets.QRadioButton(self.tab)
        self.RGBradioButton.setGeometry(QtCore.QRect(70, 110, 111, 23))
        self.RGBradioButton.setObjectName("RGBradioButton")
        self.BGRradioButton = QtWidgets.QRadioButton(self.tab)
        self.BGRradioButton.setGeometry(QtCore.QRect(230, 110, 111, 23))
        self.BGRradioButton.setObjectName("BGRradioButton")
        self.RedcomboBox = QtWidgets.QComboBox(self.tab)
        self.RedcomboBox.setGeometry(QtCore.QRect(180, 150, 191, 25))
        self.RedcomboBox.setObjectName("RedcomboBox")
        self.NIRcomboBox = QtWidgets.QComboBox(self.tab)
        self.NIRcomboBox.setGeometry(QtCore.QRect(180, 190, 191, 25))
        self.NIRcomboBox.setObjectName("NIRcomboBox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(60, 150, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(60, 190, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(60, 230, 91, 21))
        self.label_7.setObjectName("label_7")
        self.GValue = gui.QgsDoubleSpinBox(self.tab)
        self.GValue.setGeometry(QtCore.QRect(180, 230, 94, 27))
        self.GValue.setProperty("value", 2.5)
        self.GValue.setObjectName("GValue")
        self.RedRefValue = QtWidgets.QDoubleSpinBox(self.tab)
        self.RedRefValue.setGeometry(QtCore.QRect(180, 270, 91, 26))
        self.RedRefValue.setProperty("value", 2.4)
        self.RedRefValue.setObjectName("RedRefValue")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(60, 270, 111, 21))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, -10, 411, 171))
        self.label_5.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(120, 190, 66, 17))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 181, 21))
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Evi2Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Evi2Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Evi2Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Evi2Dialog)

    def retranslateUi(self, Evi2Dialog):
        _translate = QtCore.QCoreApplication.translate
        Evi2Dialog.setWindowTitle(_translate("Evi2Dialog", "EVI 2"))
        self.groupBox_2.setTitle(_translate("Evi2Dialog", "EVI 2"))
        self.label.setText(_translate("Evi2Dialog", "Raster"))
        self.RGBradioButton.setText(_translate("Evi2Dialog", "R,G,B,NIR"))
        self.BGRradioButton.setText(_translate("Evi2Dialog", "B,G,R,NIR"))
        self.label_2.setText(_translate("Evi2Dialog", "Red Band"))
        self.label_3.setText(_translate("Evi2Dialog", "NIR Band"))
        self.label_7.setText(_translate("Evi2Dialog", "Gain Factor"))
        self.label_8.setText(_translate("Evi2Dialog", "Red Reflectance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Evi2Dialog", "Tool"))
        self.label_5.setText(_translate("Evi2Dialog", "## Enhanced Vegetation Index 2 (EVI2)\n"
"\n"
"The Enhanced Vegetation Index 2 (EVI2) is a modified version of the Enhanced Vegetation Index (EVI) that does not require the blue band, making it more applicable for sensors that do not have a blue band. \n"
"EVI2 provides similar benefits to EVI in terms of vegetation monitoring, but simplifies the calculation by omitting the need for the blue band."))
        self.label_6.setText(_translate("Evi2Dialog", "<html><head/><body><p>EVI<span style=\" vertical-align:sub;\">2</span> = 2.5 × <span style=\" vertical-align:super;\">(NIR - R)</span> / <span style=\" vertical-align:sub;\">(NIR + 2.4R + 1)</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Evi2Dialog", "Help"))
from qgis import gui
