# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fishbone_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FishboneDialog(object):
    def setupUi(self, FishboneDialog):
        FishboneDialog.setObjectName("FishboneDialog")
        FishboneDialog.resize(446, 348)
        self.buttonBox = QtWidgets.QDialogButtonBox(FishboneDialog)
        self.buttonBox.setGeometry(QtCore.QRect(128, 302, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(FishboneDialog)
        self.tabWidget.setGeometry(QtCore.QRect(8, 8, 431, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 50, 85, 17))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(6, 131, 411, 111))
        self.groupBox.setObjectName("groupBox")
        self.AddressStreetComboBox = QtWidgets.QComboBox(self.groupBox)
        self.AddressStreetComboBox.setGeometry(QtCore.QRect(230, 70, 151, 25))
        self.AddressStreetComboBox.setObjectName("AddressStreetComboBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 42, 101, 17))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(98, 74, 124, 17))
        self.label_4.setObjectName("label_4")
        self.AddressComboBox = QtWidgets.QComboBox(self.groupBox)
        self.AddressComboBox.setGeometry(QtCore.QRect(150, 40, 231, 25))
        self.AddressComboBox.setObjectName("AddressComboBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(6, 9, 411, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.StreetComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.StreetComboBox.setGeometry(QtCore.QRect(140, 38, 241, 25))
        self.StreetComboBox.setObjectName("StreetComboBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(100, 72, 123, 17))
        self.label_3.setObjectName("label_3")
        self.StreetStreetComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.StreetStreetComboBox.setGeometry(QtCore.QRect(230, 68, 151, 25))
        self.StreetStreetComboBox.setObjectName("StreetStreetComboBox")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.label.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 431, 41))
        self.label_6.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(0, 180, 421, 41))
        self.label_8.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(0, 220, 361, 31))
        self.label_9.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 411, 131))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(FishboneDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(FishboneDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FishboneDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FishboneDialog)

    def retranslateUi(self, FishboneDialog):
        _translate = QtCore.QCoreApplication.translate
        FishboneDialog.setWindowTitle(_translate("FishboneDialog", "Fishbone"))
        self.label.setText(_translate("FishboneDialog", "Street Layer"))
        self.groupBox.setTitle(_translate("FishboneDialog", "Address Points"))
        self.label_2.setText(_translate("FishboneDialog", "Address Layer"))
        self.label_4.setText(_translate("FishboneDialog", "Street Name Field"))
        self.groupBox_2.setTitle(_translate("FishboneDialog", "Road Centerlines"))
        self.label_3.setText(_translate("FishboneDialog", "Street Name Field"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FishboneDialog", "Tool"))
        self.label_6.setText(_translate("FishboneDialog", "***Road Centerline***: This is a multiline featureclass that contains the road or street name eg. \"Elm\" for Elm Street."))
        self.label_8.setText(_translate("FishboneDialog", "***Address Points***: This is a point featureclass that contains the road or street name eg. \"Elm\" for Elm Street."))
        self.label_9.setText(_translate("FishboneDialog", "The tool will use the street name to join the 2 layers."))
        self.label_5.setText(_translate("FishboneDialog", "This tool is designed to create a visual representation of connections between address points and their nearest street segments based on a shared street name. By selecting an address layer and a street layer, the tool generates lines linking each address to the closest street segment. This helps in visualizing spatial adress relationships."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FishboneDialog", "Help"))
