# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fishbone_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FishboneDialog(object):
    def setupUi(self, FishboneDialog):
        FishboneDialog.setObjectName("FishboneDialog")
        FishboneDialog.resize(622, 301)
        self.buttonBox = QtWidgets.QDialogButtonBox(FishboneDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.StreetComboBox = QtWidgets.QComboBox(FishboneDialog)
        self.StreetComboBox.setGeometry(QtCore.QRect(160, 50, 211, 25))
        self.StreetComboBox.setObjectName("StreetComboBox")
        self.label = QtWidgets.QLabel(FishboneDialog)
        self.label.setGeometry(QtCore.QRect(50, 50, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FishboneDialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 101, 17))
        self.label_2.setObjectName("label_2")
        self.AddressComboBox = QtWidgets.QComboBox(FishboneDialog)
        self.AddressComboBox.setGeometry(QtCore.QRect(160, 130, 211, 25))
        self.AddressComboBox.setObjectName("AddressComboBox")
        self.label_3 = QtWidgets.QLabel(FishboneDialog)
        self.label_3.setGeometry(QtCore.QRect(100, 80, 121, 17))
        self.label_3.setObjectName("label_3")
        self.StreetStreetComboBox = QtWidgets.QComboBox(FishboneDialog)
        self.StreetStreetComboBox.setGeometry(QtCore.QRect(230, 80, 231, 25))
        self.StreetStreetComboBox.setObjectName("StreetStreetComboBox")
        self.AddressStreetComboBox = QtWidgets.QComboBox(FishboneDialog)
        self.AddressStreetComboBox.setGeometry(QtCore.QRect(230, 160, 231, 25))
        self.AddressStreetComboBox.setObjectName("AddressStreetComboBox")
        self.label_4 = QtWidgets.QLabel(FishboneDialog)
        self.label_4.setGeometry(QtCore.QRect(100, 160, 121, 17))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(FishboneDialog)
        self.buttonBox.accepted.connect(FishboneDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FishboneDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FishboneDialog)

    def retranslateUi(self, FishboneDialog):
        _translate = QtCore.QCoreApplication.translate
        FishboneDialog.setWindowTitle(_translate("FishboneDialog", "Fishbone"))
        self.label.setText(_translate("FishboneDialog", "Street Layer"))
        self.label_2.setText(_translate("FishboneDialog", "Address Layer"))
        self.label_3.setText(_translate("FishboneDialog", "Street Name Field"))
        self.label_4.setText(_translate("FishboneDialog", "Street Name Field"))
