# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Flipper_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlipperDialog(object):
    def setupUi(self, FlipperDialog):
        FlipperDialog.setObjectName("FlipperDialog")
        FlipperDialog.resize(445, 183)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlipperDialog.sizePolicy().hasHeightForWidth())
        FlipperDialog.setSizePolicy(sizePolicy)
        self.FlipperRastercomboBox = QtWidgets.QComboBox(FlipperDialog)
        self.FlipperRastercomboBox.setGeometry(QtCore.QRect(10, 10, 421, 25))
        self.FlipperRastercomboBox.setObjectName("FlipperRastercomboBox")
        self.next_button = QtWidgets.QPushButton(FlipperDialog)
        self.next_button.setGeometry(QtCore.QRect(330, 100, 89, 25))
        self.next_button.setText("")
        self.next_button.setObjectName("next_button")
        self.prev_button = QtWidgets.QPushButton(FlipperDialog)
        self.prev_button.setGeometry(QtCore.QRect(30, 100, 89, 25))
        self.prev_button.setText("")
        self.prev_button.setObjectName("prev_button")
        self.play_button = QtWidgets.QPushButton(FlipperDialog)
        self.play_button.setGeometry(QtCore.QRect(130, 100, 89, 25))
        self.play_button.setText("")
        self.play_button.setObjectName("play_button")
        self.stop_button = QtWidgets.QPushButton(FlipperDialog)
        self.stop_button.setGeometry(QtCore.QRect(230, 100, 89, 25))
        self.stop_button.setText("")
        self.stop_button.setObjectName("stop_button")
        self.band_label = QtWidgets.QLabel(FlipperDialog)
        self.band_label.setGeometry(QtCore.QRect(170, 40, 67, 16))
        self.band_label.setObjectName("band_label")
        self.min_spinbox = QtWidgets.QDoubleSpinBox(FlipperDialog)
        self.min_spinbox.setGeometry(QtCore.QRect(80, 60, 101, 26))
        self.min_spinbox.setObjectName("min_spinbox")
        self.max_spinbox = QtWidgets.QDoubleSpinBox(FlipperDialog)
        self.max_spinbox.setGeometry(QtCore.QRect(290, 60, 101, 26))
        self.max_spinbox.setProperty("value", 1.0)
        self.max_spinbox.setObjectName("max_spinbox")
        self.band_slider = QtWidgets.QSlider(FlipperDialog)
        self.band_slider.setGeometry(QtCore.QRect(40, 140, 371, 20))
        self.band_slider.setOrientation(QtCore.Qt.Horizontal)
        self.band_slider.setObjectName("band_slider")

        self.retranslateUi(FlipperDialog)
        QtCore.QMetaObject.connectSlotsByName(FlipperDialog)

    def retranslateUi(self, FlipperDialog):
        _translate = QtCore.QCoreApplication.translate
        FlipperDialog.setWindowTitle(_translate("FlipperDialog", "Dialog"))
        self.band_label.setText(_translate("FlipperDialog", "Band: 1"))
        self.min_spinbox.setPrefix(_translate("FlipperDialog", "Min: "))
        self.max_spinbox.setPrefix(_translate("FlipperDialog", "Max: "))
