# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ndvi_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NdviDialog(object):
    def setupUi(self, NdviDialog):
        NdviDialog.setObjectName("NdviDialog")
        NdviDialog.resize(446, 348)
        self.buttonBox = QtWidgets.QDialogButtonBox(NdviDialog)
        self.buttonBox.setGeometry(QtCore.QRect(128, 302, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(NdviDialog)
        self.tabWidget.setGeometry(QtCore.QRect(8, 8, 431, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(6, 9, 411, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.RastercomboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.RastercomboBox.setGeometry(QtCore.QRect(110, 40, 261, 25))
        self.RastercomboBox.setObjectName("RastercomboBox")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 91, 20))
        self.label.setObjectName("label")
        self.refreshButton = QtWidgets.QToolButton(self.groupBox_2)
        self.refreshButton.setGeometry(QtCore.QRect(380, 40, 26, 24))
        self.refreshButton.setText("")
        self.refreshButton.setObjectName("refreshButton")
        self.RGBradioButton = QtWidgets.QRadioButton(self.tab)
        self.RGBradioButton.setGeometry(QtCore.QRect(80, 110, 111, 23))
        self.RGBradioButton.setObjectName("RGBradioButton")
        self.BGRradioButton = QtWidgets.QRadioButton(self.tab)
        self.BGRradioButton.setGeometry(QtCore.QRect(240, 110, 111, 23))
        self.BGRradioButton.setObjectName("BGRradioButton")
        self.RedcomboBox = QtWidgets.QComboBox(self.tab)
        self.RedcomboBox.setGeometry(QtCore.QRect(180, 150, 191, 25))
        self.RedcomboBox.setObjectName("RedcomboBox")
        self.NIRcomboBox = QtWidgets.QComboBox(self.tab)
        self.NIRcomboBox.setGeometry(QtCore.QRect(180, 190, 191, 25))
        self.NIRcomboBox.setObjectName("NIRcomboBox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(80, 190, 71, 17))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 431, 41))
        self.label_6.setText("")
        self.label_6.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(0, 180, 421, 41))
        self.label_8.setText("")
        self.label_8.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(0, 220, 361, 31))
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 421, 251))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(NdviDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(NdviDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NdviDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NdviDialog)

    def retranslateUi(self, NdviDialog):
        _translate = QtCore.QCoreApplication.translate
        NdviDialog.setWindowTitle(_translate("NdviDialog", "NDVI"))
        self.groupBox_2.setTitle(_translate("NdviDialog", "NDVI"))
        self.label.setText(_translate("NdviDialog", "4 Band Raster"))
        self.RGBradioButton.setText(_translate("NdviDialog", "R,G,B,NIR"))
        self.BGRradioButton.setText(_translate("NdviDialog", "B,G,R,NIR"))
        self.label_2.setText(_translate("NdviDialog", "Red Band"))
        self.label_3.setText(_translate("NdviDialog", "NIR Band"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("NdviDialog", "Tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("NdviDialog", "Help"))
