# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ndwi_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NdwiDialog(object):
    def setupUi(self, NdwiDialog):
        NdwiDialog.setObjectName("NdwiDialog")
        NdwiDialog.resize(446, 348)
        self.buttonBox = QtWidgets.QDialogButtonBox(NdwiDialog)
        self.buttonBox.setGeometry(QtCore.QRect(128, 302, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(NdwiDialog)
        self.tabWidget.setGeometry(QtCore.QRect(8, 8, 431, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(6, 9, 411, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.RastercomboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.RastercomboBox.setGeometry(QtCore.QRect(110, 40, 261, 25))
        self.RastercomboBox.setObjectName("RastercomboBox")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(50, 40, 51, 20))
        self.label.setObjectName("label")
        self.refreshButton = QtWidgets.QToolButton(self.groupBox_2)
        self.refreshButton.setGeometry(QtCore.QRect(380, 40, 26, 24))
        self.refreshButton.setText("")
        self.refreshButton.setObjectName("refreshButton")
        self.GradioButton = QtWidgets.QRadioButton(self.tab)
        self.GradioButton.setGeometry(QtCore.QRect(80, 110, 111, 23))
        self.GradioButton.setObjectName("GradioButton")
        self.RGBradioButton = QtWidgets.QRadioButton(self.tab)
        self.RGBradioButton.setGeometry(QtCore.QRect(240, 110, 111, 23))
        self.RGBradioButton.setObjectName("RGBradioButton")
        self.GreencomboBox = QtWidgets.QComboBox(self.tab)
        self.GreencomboBox.setGeometry(QtCore.QRect(180, 150, 191, 25))
        self.GreencomboBox.setObjectName("GreencomboBox")
        self.NIRcomboBox = QtWidgets.QComboBox(self.tab)
        self.NIRcomboBox.setGeometry(QtCore.QRect(180, 190, 191, 25))
        self.NIRcomboBox.setObjectName("NIRcomboBox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 81, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(90, 190, 71, 17))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 431, 41))
        self.label_6.setText("")
        self.label_6.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(0, 180, 421, 41))
        self.label_8.setText("")
        self.label_8.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(0, 220, 361, 31))
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 411, 171))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(NdwiDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(NdwiDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NdwiDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NdwiDialog)

    def retranslateUi(self, NdwiDialog):
        _translate = QtCore.QCoreApplication.translate
        NdwiDialog.setWindowTitle(_translate("NdwiDialog", "NDWI"))
        self.groupBox_2.setTitle(_translate("NdwiDialog", "NDVI"))
        self.label.setText(_translate("NdwiDialog", "Raster"))
        self.GradioButton.setText(_translate("NdwiDialog", "G,NIR"))
        self.RGBradioButton.setText(_translate("NdwiDialog", "*,G,*,NIR"))
        self.label_2.setText(_translate("NdwiDialog", "Green Band"))
        self.label_3.setText(_translate("NdwiDialog", "NIR Band"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("NdwiDialog", "Tool"))
        self.label_5.setText(_translate("NdwiDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Generate NDWI:</span> This tool calculates the Normalized Difference Water Index (NDWI) from satellite imagery to assess water content in vegetation and monitor water bodies. NDWI is used in remote sensing to distinguish water bodies from vegetation and soil, helping in water resource management and environmental monitoring. </p><p>Chose one of the more common band configurations or choose your green and NIR bands manualy.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("NdwiDialog", "Help"))
